#!/bin/bash

ROOT=`dirname $0`

# Setup symlinks for includes
for inc in include include_cz include_hu; do
  rm -r -f $ROOT/assets/$inc
  mkdir -p $ROOT/assets/$inc
  for i in ../$ROOT/$inc/*; do
    ln -s "../../../$inc/`basename $i`" $ROOT/assets/$inc/"`basename "$i" | sed 's/^_/x/'`"
  done
  rm -f $ROOT/assets/$inc/index.htm
done

### Setup symlinks for docs

# SK
rm -f $ROOT/assets/docs/*
for i in kat-2001-03-28.htm ord-inv.htm ord-k3.htm ord-km.htm ord-vesp.htm \
         uvodmp.htm kat-2001-04-04.htm ord-k0.htm ord-k4.htm ord-komp.htm \
         smernice_lh.htm ord-k1.htm ord-k5.htm ord-pc.htm \
         smernice_lrk.htm laudis-canticum.htm ord-k2.htm ord-k6.htm \
         ord-rch.htm ukonkaj.htm; do
  cp $ROOT/../docs/$i $ROOT/assets/docs/$i
done

# CZ
rm -f $ROOT/assets/cz/docs/*
mkdir -p $ROOT/assets/cz/docs
rm -f $ROOT/assets/cz/docs/*
for i in full_ordinar.htm ord-k0.htm ord-k2.htm ord-k4.htm ord-k6.htm \
         ord-komp.htm ord-rch.htm ord-inv.htm ord-k1.htm ord-k3.htm ord-k5.htm \
         ord-km.htm ord-pc.htm ord-vesp.htm; do
  cp $ROOT/../cz/docs/$i $ROOT/assets/cz/docs/$i
done


# HU
rm -f $ROOT/assets/hu/docs/*
mkdir -p $ROOT/assets/hu/docs
for i in ord-k1.htm ord-k4.htm ord-km.htm ord-rch.htm ukonkaj.htm \
         ord-inv.htm ord-k2.htm ord-k5.htm ord-komp.htm ord-vesp.htm uvodmp.htm \
         ord-k0.htm ord-k3.htm ord-k6.htm ord-pc.htm; do
  cp $ROOT/../hu/docs/$i $ROOT/assets/hu/docs/$i
done

if [ -f $ROOT/../hu/docs/smernice_lh.htm ]; then
  cp $ROOT/assets/hu/docs/smernice_lh.htm $ROOT/assets/hu/docs/smernice_lh.htm
else
  cp $ROOT/assets/docs/smernice_lh.htm $ROOT/assets/hu/docs/smernice_lh.htm
fi

rm -f $ROOT/assets/katechezy.htm
cp $ROOT/../katechezy.htm $ROOT/assets/katechezy.htm

rm -f $ROOT/assets/breviar-web.cfg $ROOT/assets/breviar-android.cfg
ln -s $ROOT/../../cgi-bin/breviar-android.cfg $ROOT/assets/breviar-web.cfg
ln -s $ROOT/../../cgi-bin/breviar-android.cfg $ROOT/assets/breviar-android.cfg

pushd $ROOT/assets
patch -p0 --merge <../assets.diff
popd

