USE [master]
GO

/****** Object:  Database [dkc]    Script Date: 07/12/2013 11:46:47 ******/
CREATE DATABASE [dkc] ON  PRIMARY 
( NAME = N'dkc', FILENAME = N'D:\databases\db_files\dkc.mdf' , SIZE = 24768KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dkc_log', FILENAME = N'D:\databases\db_files\dkc_1.ldf' , SIZE = 22656KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dkc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dkc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dkc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dkc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dkc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dkc] SET ARITHABORT OFF 
GO

ALTER DATABASE [dkc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dkc] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dkc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dkc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dkc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dkc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dkc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dkc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dkc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dkc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dkc] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dkc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dkc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dkc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dkc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dkc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dkc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dkc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dkc] SET  READ_WRITE 
GO

ALTER DATABASE [dkc] SET RECOVERY FULL 
GO

ALTER DATABASE [dkc] SET  MULTI_USER 
GO

ALTER DATABASE [dkc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dkc] SET DB_CHAINING OFF 
GO


